### PR TITLE
Better tick optimization, Closes #6

### LINKED ISSUE #2: Clean up code
Spacing is off for one and I'm not sure if LUA styles even use tabs.

### LINKED ISSUE #5: Attempt to mutate global
Just a friendly heads up that this will error.

Not allowed to mutate global in on_load

### LINKED ISSUE #6: Tick optimiztion
https://github.com/will-janz/factorio-simple-saplings/blob/master/control.lua#L28

Not exactly what you were talking about but this references #3

Mostly pseudo code but for way better optimization use game.tick + growth time as index and use a sequential table of tables as the value. This will greatly increase speed as you won't have to loop through your table every tick/xxxticks
```lua
local grow_on_tick = game.tick+max_grow_time
--Get or create the global tick to grow on
global.growing_times[grow_on_tick] = global.growing_times[grow_on_tick] or {}
--local reference because speed and things
local data = global.growing_times[grow_on_tick]
--since all we need is the position table stick it here. Alternatively can still send as a table of data containing more data if needed too "i.e. a reference to sapling to avoid having to do an expensive surface.find
data[#data+1] = event.created_entity.position,
```

Then adjust your tick handler to something like
```lua
--We have some logic to do on this tick!
if global.grow_on_tick[event.tick] then
for _, position in ipairs(global.grow_on_tick[event.tick]) do
--grow tree at position code
end
--clean up the global table
global.grow_on_tick[event.tick] = nil
```

Don't forget to also handle deleting trees. For this you will still have to loop through the whole list but since you will only be doing it on sapling destroy not a problem.  Alternatively you could create a second list with just positions to use for cross references but I don't see any point in that.

### PR DESCRIPTION
**Pull request by Nexela**
Lints cleanly, Closes #2
Remove on_load potential mutate error, Closes #5

Untested, Let me know what you think!

### CODE REVIEW

**Review by will-janz — APPROVED** [review]
Looks great! The only issue I could see arising would be if a tick that a sapling was supposed to grow at was skipped.

**Comment by will-janz** [comment]
Merged into develop via command line. Will now playtest.

**Comment by Nexela** [comment]
> Looks great! The only issue I could see arising would be if a tick that a sapling was supposed to grow at was skipped.

Ticks don't get skipped

**Comment by Nexela** [comment]
Also pull requests will self close after they get merged into the target branch.

**Comment by will-janz** [comment]
Ah, TIL. Tested and fixed a few bugs where data wasn't getting passed around to where it needed to be, works well now!

**Comment by will-janz** [comment]
So this is the most successful GitHub repo I've ever done, if I screwed anything up (aside from closing the PR prematurely), let me know! And thank you for the help!

**Comment by Nexela** [comment]
No worries, If a commit refrences an issue/pull request like this

Closes #5 
When it gets pulled into master it will automatically close the issue :)

**Comment by will-janz** [comment]
Alrighty. I've done a full on release, fingers crossed!

**Pull request closed without merging**
